function setActualMoveIndex(index) {
  contextValues.actualMoveIndex = index;
}
function setActualOptionIndex(index) {
  contextValues.actualOptionIndex = index;
}
const moves = [
  {
    index: 0,
    letters: "RĘCZONA",
    move: "-> Pawel_Mazurek            RĘCZONA  0   ",
    nick: "Pawel_Mazurek",
    pointsBefore: "0",
    choiceOptions: [
      {
        coordinates: "*8C",
        evaluate: "best",
        freeLetters: "",
        index: 0,
        movePoints: "84",
        percent: "76.69%",
        word: "RĘCZONA",
      },
      {
        coordinates: "8H",
        evaluate: "8.16",
        freeLetters: "",
        index: 1,
        movePoints: "76",
        percent: "74.32%",
        word: "RĘCZONA",
      },
      {
        coordinates: "8G",
        evaluate: "11.7",
        freeLetters: "",
        index: 2,
        movePoints: "76",
        percent: "72.85%",
        word: "RĘCZONA",
      },
    ],
  },
  {
    index: 1,
    letters: "KOLEŃ",
    move: "-> Maciej_Skrzypczak        KOLEŃ    0   ",
    nick: "Maciej_Skrzypczak",
    pointsBefore: "0",
    choiceOptions: [
      {
        coordinates: "9F",
        evaluate: "best",
        freeLetters: "KOL",
        index: 0,
        movePoints: "32",
        percent: "25.08%",
        word: "EŃ",
      },
      {
        coordinates: "F8",
        evaluate: "12.7",
        freeLetters: "KOL",
        index: 1,
        movePoints: "23",
        percent: "20.57%",
        word: "(Z)EŃ",
      },
    ],
  },
  {
    index: 2,
    letters: "HONOUAŚ",
    move: "-> Pawel_Mazurek            HONOUAŚ  84  ",
    nick: "Pawel_Mazurek",
    pointsBefore: "84",
    choiceOptions: [
      {
        coordinates: "*6J",
        evaluate: "best",
        freeLetters: "NOUAŚ",
        index: 0,
        movePoints: "28",
        percent: "74.39%",
        word: "HO",
      },
      {
        coordinates: "E5",
        evaluate: "3.63",
        freeLetters: "HOU",
        index: 1,
        movePoints: "20",
        percent: "73.88%",
        word: "NOŚ(C)A",
      },
    ],
  },
];
function setMoves(moves) {
  contextValues.moves = moves;
}
export const contextValues = {
  moves,
  actualMoveIndex: 0,
  actualOptionIndex: 0,
  setActualMoveIndex,
  setActualOptionIndex,
  setMoves,
  getActualMove: () => ({
    letters: "ABCD",
  }),
};

export const txtFile = `Game Report
Generated by Quackle crossword game AI and analysis software
http://quackle.org

Pawel_Mazurek: Turn 1
   A B C D E F G H I J K L M N O   -> Pawel_Mazurek            RĘCZONA  0   
   ------------------------------     Maciej_Skrzypczak        ?CEGORU   0   
 1|=     '       =       '     =| --Championship Player's choices (your play: 1)
 2|  -       "       "       -  | best *8C RĘCZONA 84 76.69% 
 3|    -       '   '       -    |  8.16 8H RĘCZONA 76 74.32% 
 4|'     -       '       -     '|  11.7 8G RĘCZONA 76 72.85% 
 5|        -           -        |  12.4 8D RĘCZONA 76 72.26% 
 6|  "       "       "       "  |  13.8 8E RĘCZONA 74 72.00% 
 7|    '       '   '       '    |  14.3 8F RĘCZONA 76 71.71% 
 8|=     '       -       '     =|  17.2 8B RĘCZONA 78 69.93% 
 9|    '       '   '       '    | --Tracking-----------------------------------
10|  "       "       "       "  | ??AAAAAAAAĄBBCCĆDDDEEEEEEEFGGHHIIIIIIIIJJKKK
11|        -           -        | LLLŁŁMMMNNNNŃOOOOOÓPPPRRRSSSSŚTTTUUWWWWYYYYZ
12|'     -       '       -     '| ZZZŹŻ  93
13|    -       '   '       -    |
14|  -       "       "       -  |
15|=     '       =       '     =|
   ------------------------------

Maciej_Skrzypczak: Turn 1
   A B C D E F G H I J K L M N O      Pawel_Mazurek            EFIJPRW   84  
   ------------------------------  -> Maciej_Skrzypczak        KOLEŃ    0   
 1|=     '       =       '     =| --Championship Player's choices (your play: 3)
 2|  -       "       "       -  | best  9F EŃ    32 25.08% KOL
 3|    -       '   '       -    |  12.7 F8 (Z)EŃ 23 20.57% KOL
 4|'     -       '       -     '|  13.4*7G KOLEŃ 29 19.91% 
 5|        -           -        |  14.5 E8 (C)LEŃ 24 19.89% KO
 6|  "       "       "       "  |  14.3 7I KOLEŃ 27 19.87% 
 7|    '       '   '       '    |  16.7 7I LEŃ   17 19.65% KO
 8|=   R Ę C Z O N A     '     =|  15.8 7I KLEŃ  19 19.59% O
 9|    '       '   '       '    |  16.7 G7 K(O)Ń 19 19.30% OLE
10|  "       "       "       "  |  15.4 9G KOLEŃ 29 19.17% 
11|        -           -        |  17.8 9I LEŃ   17 19.15% KO
12|'     -       '       -     '| --Tracking-----------------------------------
13|    -       '   '       -    | ??AAAAAAAAĄBBCCĆDDDEEEEEEFGGHHIIIIIIIIJJKKLL
14|  -       "       "       -  | ŁŁMMMNNNNOOOOÓPPPRRRSSSSŚTTTUUWWWWYYYYZZZZŹŻ  88
15|=     '       =       '     =|
   ------------------------------

Pawel_Mazurek: Turn 2
   A B C D E F G H I J K L M N O   -> Pawel_Mazurek            HONOUAŚ  84  
   ------------------------------     Maciej_Skrzypczak        AAEIIJR   29  
 1|=     '       =       '     =| --Championship Player's choices (your play: 1)
 2|  -       "       "       -  | best *6J HO       28 74.39% NOUAŚ
 3|    -       '   '       -    |  3.63 E5 NOŚ(C)A 20 73.88% HOU
 4|'     -       '       -     '|  4.42 E5 NOŚ(C)O 20 73.69% HUA
 5|        -           -        |  3.14 G6 U(KO)Ś  16 73.46% HONOA
 6|  "       "       "       "  |  5.64 F7 O(Z)ON   20 72.58% HUAŚ
 7|    '       K O L E Ń   '    |  6.45 E8 (C)HANU  20 72.56% OOŚ
 8|=   R Ę C Z O N A     '     =|  7.55 F7 O(Z)ONU  23 72.37% HAŚ
 9|    '       '   '       '    |  5.42 6K OŚ      14 72.13% HNOUA
10|  "       "       "       "  |  9.06 E8 (C)HOANO 18 71.75% UŚ
11|        -           -        |  10.0 C4 HONO(R)U 14 71.66% AŚ
12|'     -       '       -     '| --Tracking-----------------------------------
13|    -       '   '       -    | ??AAAAAAAĄBBCCĆDDDEEEEEEFGGHIIIIIIIIJJKKLLŁŁ
14|  -       "       "       -  | MMMNNNOOÓPPPRRRSSSSTTTUWWWWYYYYZZZZŹŻ  81
15|=     '       =       '     =|
   ------------------------------

Maciej_Skrzypczak: Turn 2
   A B C D E F G H I J K L M N O      Pawel_Mazurek            AEENOŚU  112 
   ------------------------------  -> Maciej_Skrzypczak        EOK       29  
 1|=     '       =       '     =| --Championship Player's choices (your play: 1)
 2|  -       "       "       -  | best *5J EKO      33 20.21% 
 3|    -       '   '       -    |  1.66 5K KEO      28 19.69% 
 4|'     -       '       -     '|  9.19 K5 K(OŃ)   20 17.74% EO
 5|        -           -        |  8.84 7F O(KOLEŃ) 16 17.38% EK
 6|  "       "       H O     "  |  9.75 5K KO       26 17.13% E
 7|    '       K O L E Ń   '    |  11.2 9H OK       15 17.02% E
 8|=   R Ę C Z O N A     '     =|  11.1 K4 OK(OŃ)  22 16.91% E
 9|    '       '   '       '    |  10.6 9F EKO      18 16.89% 
10|  "       "       "       "  |  11.2 9H EKO      16 16.49% 
11|        -           -        |  13.4 6E EKO      12 15.95% 
12|'     -       '       -     '| --Tracking-----------------------------------
13|    -       '   '       -    | ??AAAAAAAAĄBBCCĆDDDEEEEEFGGHIIIIIIIIJJKLLŁŁM
14|  -       "       "       -  | MMNNNNOOÓPPPRRRSSSSŚTTTUUWWWWYYYYZZZZŹŻ  83
15|=     '       =       '     =|
   ------------------------------

Pawel_Mazurek: Turn 3
   A B C D E F G H I J K L M N O   -> Pawel_Mazurek            ROŚNAAU  112 
   ------------------------------     Maciej_Skrzypczak        AAACFPY   62  
 1|=     '       =       '     =| --Championship Player's choices (your play: 1)
 2|  -       "       "       -  | best *F8 (Z)AŚ   17 77.81% RONAU
 3|    -       '   '       -    |  7.86 E5 NOŚ(C)A 20 75.35% RAU
 4|'     -       '       -     '|  7.57 4L OŚ      16 74.85% RNAAU
 5|        -         E K O      |  9.82 G6 U(KO)ŚNA 18 74.44% ROA
 6|  "       "       H O     "  |  10.4 4K ORANA    27 74.02% ŚU
 7|    '       K O L E Ń   '    |  12.1 4K ORNA     23 73.89% ŚAU
 8|=   R Ę C Z O N A     '     =|  11.8 G6 U(KO)Ś  16 73.48% RONAA
 9|    '       '   '       '    |  15.3 4K ORU      25 72.51% ŚNAA
10|  "       "       "       "  |  16.1 9F ARO      14 72.18% ŚNAU
11|        -           -        |  15.4 4K ONA      21 72.17% RŚAU
12|'     -       '       -     '| --Tracking-----------------------------------
13|    -       '   '       -    | ??AAAAAAĄBBCCĆDDDEEEEEFGGHIIIIIIIIJJKLLŁŁMMM
14|  -       "       "       -  | NNNOÓPPPRRSSSSTTTUWWWWYYYYZZZZŹŻ  76
15|=     '       =       '     =|
   ------------------------------

Maciej_Skrzypczak: Turn 3
   A B C D E F G H I J K L M N O      Pawel_Mazurek            ANORTUZ   129 
   ------------------------------  -> Maciej_Skrzypczak        AĆIŁMM  62  
 1|=     '       =       '     =| --Championship Player's choices (your play: 6)
 2|  -       "       "       -  | best  9I  ĆMIŁ    33 29.10% AM
 3|    -       '   '       -    |  1.34 L1  ĆMIŁ(O) 38 28.39% AM
 4|'     -       '       -     '|  2.53 9I  ĆMIŁA   35 27.76% M
 5|        -         E K O      |  6.72 9I  ĆMI      30 26.13% AŁM
 6|  "       "       H O     "  |  12.5 9H  IMĆ      21 24.43% AŁM
 7|    '       K O L E Ń   '    |  10.1*9I  ĆMIŁAM  37 24.35% 
 8|=   R Ę C Z O N A     '     =|  13.3 F8  (ZAŚ)MIAĆ 29 23.94% ŁM
 9|    '     A '   '       '    |  13.8 9I  ĆMAMI    34 23.12% Ł
10|  "       Ś       "       "  |  14.9 9I  MAMIĆ    27 22.99% Ł
11|        -           -        |  17.5 10F (Ś)MIAĆ 27 22.23% ŁM
12|'     -       '       -     '| --Tracking-----------------------------------
13|    -       '   '       -    | ??AAAAAAĄBBCCDDDEEEEEFGGHIIIIIIIJJKLLŁMNNNNO
14|  -       "       "       -  | OÓPPPRRRSSSSTTTUUWWWWYYYYZZZZŹŻ  75
15|=     '       =       '     =|
   ------------------------------

Pawel_Mazurek: Turn 4
   A B C D E F G H I J K L M N O   -> Pawel_Mazurek            AURAONY   129 
   ------------------------------     Maciej_Skrzypczak        ?DSUWZŹ  99  
 1|=     '       =       '     =| --Championship Player's choices (your play: 3)
 2|  -       "       "       -  | 0.177 L8  A(Ł)UNY 22 72.02% RAO
 3|    -       '   '       -    | 0.755 L8  U(Ł)ANY 26 71.91% RAO
 4|'     -       '       -     '| best *4K  ORANY    31 71.77% UA
 5|        -         E K O      |  1.79 N9  (M)ARUNY 24 71.34% AO
 6|  "       "       H O     "  |  3.23 D3  AURYN(Ę) 26 70.86% AO
 7|    '       K O L E Ń   '    |  3.01 10M AU       23 70.59% RAONY
 8|=   R Ę C Z O N A     '     =|  3.90 L8  U(Ł)ANA 24 70.43% ROY
 9|    '     A '   Ć M I Ł A M  |  3.80 10M AUR      24 70.13% AONY
10|  "       Ś       "       "  |  5.42 4K  ORANA    27 69.76% UY
11|        -           -        |  5.59 10M AUA      24 69.09% RONY
12|'     -       '       -     '| --Tracking-----------------------------------
13|    -       '   '       -    | ??AAAAĄBBCCDDDEEEEEFGGHIIIIIIIJJKLLŁMNNNOÓPP
14|  -       "       "       -  | PRRSSSSTTTUWWWWYYYZZZZŹŻ  68
15|=     '       =       '     =|
   ------------------------------

Maciej_Skrzypczak: Turn 4
   A B C D E F G H I J K L M N O      Pawel_Mazurek            AIKNOSU   160 
   ------------------------------  -> Maciej_Skrzypczak        BET       99  
 1|=     '       =       '     =| --Championship Player's choices (your play: 4)
 2|  -       "       "       -  | best  3M BET     26 23.37% 
 3|    -       '   '       -    |  1.78 8M BET     25 22.33% 
 4|'     -       '     O R A N Y|  6.13 6F BET     20 20.95% 
 5|        -         E K O      |  5.66*O1 BET(Y)  24 20.53% 
 6|  "       "       H O     "  |  10.2 7B BET     17 19.75% 
 7|    '       K O L E Ń   '    |  11.0 M1 BET(A)  14 19.26% 
 8|=   R Ę C Z O N A     '     =|  13.1 H4 BET(ON) 11 18.56% 
 9|    '     A '   Ć M I Ł A M  |  15.5 6G ET      11 18.17% B
10|  "       Ś       "       "  |  15.1 3M BE      18 18.05% T
11|        -           -        |  14.9 6F BE      14 17.62% T
12|'     -       '       -     '| --Tracking-----------------------------------
13|    -       '   '       -    | ??AAAAAĄBCCDDDEEEEFGGHIIIIIIIJJKLLŁMNNNOÓPPP
14|  -       "       "       -  | RRSSSSTTUUWWWWYYYZZZZŹŻ  67
15|=     '       =       '     =|
   ------------------------------

Pawel_Mazurek: Turn 5
   A B C D E F G H I J K L M N O   -> Pawel_Mazurek            AUWAWES   160 
   ------------------------------     Maciej_Skrzypczak        AEILPSŹ  123 
 1|=     '       =       '     B| --Championship Player's choices (your play: 1)
 2|  -       "       "       - E| 0.305*B8  WSUWA   26 74.53% AE
 3|    -       '   '       -   T| best  N2  WE(N)US 25 73.73% AAW
 4|'     -       '     O R A N Y|  2.32 B5  WSUWA   22 73.40% AE
 5|        -         E K O      |  5.32 B6  SUWA    21 71.97% AWE
 6|  "       "       H O     "  |  4.77 L8  S(Ł)AWA 16 71.69% UWE
 7|    '       K O L E Ń   '    |  5.90 10M SUW     24 71.54% AAWE
 8|=   R Ę C Z O N A     '     =|  4.71 N2  WE(N)A  15 71.27% UAWS
 9|    '     A '   Ć M I Ł A M  |  9.40 10M AUA     24 69.94% WWES
10|  "       Ś       "       "  |  9.93 N6  SWE(M)U 16 69.26% AAW
11|        -           -        |  10.3 N2  WA(N)A  15 69.11% UWES
12|'     -       '       -     '| --Tracking-----------------------------------
13|    -       '   '       -    | ??AAAĄBCCDDDEEEFGGHIIIIIIIJJKLLŁMNNNOÓPPPRRS
14|  -       "       "       -  | SSTTUWWYYYZZZZŹŻ  60
15|=     '       =       '     =|
   ------------------------------

Maciej_Skrzypczak: Turn 5
   A B C D E F G H I J K L M N O      Pawel_Mazurek            AAEEIPY   186 
   ------------------------------  -> Maciej_Skrzypczak        A         123 
 1|=     '       =       '     B| --Championship Player's choices (your play: 1)
 2|  -       "       "       - E| best *xch ??????? 0 12.92% A
 3|    -       '   '       -   T|  2.18 J9  (M)A    5 12.32% 
 4|'     -       '     O R A N Y|  3.34 N9  (M)A    5 12.31% 
 5|        -         E K O      |  3.06 12A A(A)    3 11.97% 
 6|  "       "       H O     "  |  2.64 10A A(U)    4 11.94% 
 7|    '       K O L E Ń   '    |  2.60 12B (A)A    2 11.92% 
 8|= W R Ę C Z O N A     '     =|  4.44 M3  A(A)    4 11.46% 
 9|  S '     A '   Ć M I Ł A M  |  5.33 N8  A(M)    3 11.30% 
10|  U       Ś       "       "  |  5.14 M9  (A)A    2 11.26% 
11|  W     -           -        |  4.52 L3  A(RO)   3 11.12% 
12|' A   -       '       -     '| --Tracking-----------------------------------
13|    -       '   '       -    | ??AAAĄBCCDDDEEEEFGGHIIIIIIIJJKLLŁMNNNOÓPPPRR
14|  -       "       "       -  | SSSTTUWWYYYZZZZŹŻ  61
15|=     '       =       '     =|
   ------------------------------

Pawel_Mazurek: Turn 6
   A B C D E F G H I J K L M N O   -> Pawel_Mazurek            EAIIICŁ  186 
   ------------------------------     Maciej_Skrzypczak        ?AĄIJSW  123 
 1|=     '       =       '     B| --Championship Player's choices (your play: 1)
 2|  -       "       "       - E| best *N2  CE(N)IŁA  39 87.17% II
 3|    -       '   '       -   T|  2.45 N2  CE(N)IŁ   37 86.07% AII
 4|'     -       '     O R A N Y|  7.69 N6  IŁA(M)I   12 84.05% EIC
 5|        -         E K O      |  10.2 13B ŁACIE     26 83.05% II
 6|  "       "       H O     "  |  10.8 10J II         11 82.70% EAICŁ
 7|    '       K O L E Ń   '    |  14.6 N9  (M)AICIE   20 81.42% IŁ
 8|= W R Ę C Z O N A     '     =|  14.8 12A Ł(A)CIE   22 81.23% AII
 9|  S '     A '   Ć M I Ł A M  |  16.6 B8  (WSUWA)ŁA 22 80.47% EIIIC
10|  U       Ś       "       "  |  17.9 A12 ACIE       21 80.20% IIŁ
11|  W     -           -        |  16.0 F8  (ZAŚ)CIEŁA 21 79.90% II
12|' A   -       '       -     '| --Tracking-----------------------------------
13|    -       '   '       -    | ??AAAĄBCDDDEEEFGGHIIIIJJKLLMNNNOÓPPPRRSSSTTU
14|  -       "       "       -  | WWYYYZZZZŹŻ  55
15|=     '       =       '     =|
   ------------------------------

Maciej_Skrzypczak: Turn 6
   A B C D E F G H I J K L M N O      Pawel_Mazurek            AGIINÓP  225 
   ------------------------------  -> Maciej_Skrzypczak        KLAT      123 
 1|=     '       =       '     B| --Championship Player's choices (your play: 2)
 2|  -       "       "       C E| 0.377 A12 TALK    32 8.010% 
 3|    -       '   '       - E T| best *A12 KLAT    32 7.899% 
 4|'     -       '     O R A N Y|  9.47 12A T(A)LK  18 6.186% A
 5|        -         E K O   I  |  10.8 12A L(A)TKA 20 5.550% 
 6|  "       "       H O     Ł  |  9.05 D4  TAKL(Ę) 24 5.486% 
 7|    '       K O L E Ń   ' A  |  13.2 12A T(A)KLA 20 5.293% 
 8|= W R Ę C Z O N A     '     =|  13.5 D4  KLAT(Ę) 24 5.241% 
 9|  S '     A '   Ć M I Ł A M  |  15.7 12A T(A)KA  16 5.139% L
10|  U       Ś       "       "  |  16.2 12A K(A)TA  16 4.817% L
11|  W     -           -        |  19.2 3M  K(ET)   16 4.691% LAT
12|' A   -       '       -     '| --Tracking-----------------------------------
13|    -       '   '       -    | ??AAĄBCDDDEEEFGGHIIIIIIJJLMNNNOÓPPPRRSSSTUWW
14|  -       "       "       -  | YYYZZZZŹŻ  53
15|=     '       =       '     =|
   ------------------------------

Pawel_Mazurek: Turn 7
   A B C D E F G H I J K L M N O   -> Pawel_Mazurek            IIIIDD?   225 
   ------------------------------     Maciej_Skrzypczak        ĄJPRSŹŻ 155 
 1|=     '       =       '     B| --Championship Player's choices (your play: 8)
 2|  -       "       "       C E| best  J9  (M)IDI 8  93.46% IID?
 3|    -       '   '       - E T| 0.306 N9  (M)IDI 8  93.30% IID?
 4|'     -       '     O R A N Y|  2.75 12A (KA)DI 12 92.50% IIID?
 5|        -         E K O   I  |  2.51 10J II     11 92.47% IIDD?
 6|  "       "       H O     Ł  |  3.69 10N II     9  92.29% IIDD?
 7|    '       K O L E Ń   ' A  |  4.51 8L  ID     12 92.14% IIID?
 8|= W R Ę C Z O N A     '     =|  4.39 12A (KA)ID 12 92.13% IIID?
 9|  S '     A '   Ć M I Ł A M  |  5.01*M6  ID     14 92.04% IIID?
10|  U       Ś       "       "  |  7.05 10J ID     13 91.33% IIID?
11|  W     -           -        |  10.6 10N ID     10 90.15% IIID?
12|K A   -       '       -     '| --Tracking-----------------------------------
13|L   -       '   '       -    | ?AAĄBCDEEEFGGHIIJJLMNNNOÓPPPRRSSSTUWWYYYZZZZ
14|A -       "       "       -  | ŹŻ  46
15|T     '       =       '     =|
   ------------------------------

Maciej_Skrzypczak: Turn 7
   A B C D E F G H I J K L M N O      Pawel_Mazurek            ?CDIIIS   239 
   ------------------------------  -> Maciej_Skrzypczak        PUJESZ    155 
 1|=     '       =       '     B| --Championship Player's choices (your play: 1)
 2|  -       "       "       C E| best *12A (KA)PUJESZ 30 10.76% 
 3|    -       '   '       - E T| 0.327 D2  ZEPSUJ(Ę) 32 10.73% 
 4|'     -       '     O R A N Y|  6.25 O6  UJE        34 9.557% PSZ
 5|        -         E K O   I  |  6.29 E6  SU(C)ZEJ   30 9.107% P
 6|  "       "       H O   I Ł  |  7.13 10M JUS        28 8.899% PEZ
 7|    '       K O L E Ń   D A  |  7.50 E7  S(C)ZEP    22 8.873% UJ
 8|= W R Ę C Z O N A     '     =|  6.58 D4  PSUJ(Ę)   28 8.780% EZ
 9|  S '     A '   Ć M I Ł A M  |  7.23 D4  PUSZ(Ę)   24 8.491% JE
10|  U       Ś       "       "  |  5.11 N9  (M)USZEJ   34 8.449% P
11|  W     -           -        |  8.10 D4  SZUJ(Ę)   26 8.243% PE
12|K A   -       '       -     '| --Tracking-----------------------------------
13|L   -       '   '       -    | ??AAĄBCDDEEFGGHIIIIIJLMNNNOÓPPRRSSTWWYYYZZZŹ
14|A -       "       "       -  | Ż  45
15|T     '       =       '     =|
   ------------------------------

Pawel_Mazurek: Turn 8
   A B C D E F G H I J K L M N O   -> Pawel_Mazurek            IIIDPP?   239 
   ------------------------------     Maciej_Skrzypczak        ĄEHITZŻ 185 
 1|=     '       =       '     B| --Championship Player's choices (your play: 1)
 2|  -       "       "       C E| best *10M DIP    15 93.45% IIP?
 3|    -       '   '       - E T|  5.96 D5  PIP(Ę) 10 91.26% IID?
 4|'     -       '     O R A N Y|  6.93 C12 (P)IP  10 90.95% IIDP?
 5|        -         E K O   I  |  6.73 13C ID     17 90.78% IIPP?
 6|  "       "       H O   I Ł  |  7.56 15A (T)IPI 7  90.67% IDP?
 7|    '       K O L E Ń   D A  |  10.1 10J ID     13 90.33% IIPP?
 8|= W R Ę C Z O N A     '     =|  9.25 10N II     9  90.31% IDPP?
 9|  S '     A '   Ć M I Ł A M  |  10.3 3M  P(ET)  16 89.96% IIIDP?
10|  U       Ś       "       "  |  10.6 10J II     11 89.76% IDPP?
11|  W     -           -        |  11.6 J9  (M)IDI 8  89.62% IPP?
12|K A P U J E S Z       -     '| --Tracking-----------------------------------
13|L   -       '   '       -    | ?AAĄBCDEEFGGHIIJLMNNNOÓRRSSTWWYYYZZZŹŻ  38
14|A -       "       "       -  |
15|T     '       =       '     =|
   ------------------------------

Maciej_Skrzypczak: Turn 8
   A B C D E F G H I J K L M N O      Pawel_Mazurek            ?ADIIPŹ  254 
   ------------------------------  -> Maciej_Skrzypczak        SOLE      185 
 1|=     '       =       '     B| --Championship Player's choices (your play: 1)
 2|  -       "       "       C E| best *11D SOLE    34 16.87% 
 3|    -       '   '       - E T|  2.42 11D SOL     30 16.36% E
 4|'     -       '     O R A N Y|  16.1 13C EL      17 11.10% SO
 5|        -         E K O   I  |  13.2 11E OLE     28 11.04% S
 6|  "       "       H O   I Ł  |  14.7 11B (W)OLE  26 10.93% S
 7|    '       K O L E Ń   D A  |  19.5 11E EL      24 10.28% SO
 8|= W R Ę C Z O N A     '     =|  15.9 13C OLE     23 10.23% S
 9|  S '     A '   Ć M I Ł A M  |  17.2 6F  LOS     15 9.878% E
10|  U       Ś       "     D I P|  21.0 11D SE      16 9.334% OL
11|  W     -           -        |  20.9 H11 S(Z)EOL 18 9.216% 
12|K A P U J E S Z       -     '| --Tracking-----------------------------------
13|L   -       '   '       -    | ??AAĄBCDEFGGHIIIIJMNNNÓPRRSTWWYYYZZZŹŻ  38
14|A -       "       "       -  |
15|T     '       =       '     =|
   ------------------------------

Pawel_Mazurek: Turn 9
   A B C D E F G H I J K L M N O   -> Pawel_Mazurek            PIANIĄ?  254 
   ------------------------------     Maciej_Skrzypczak        CNÓSWYZ  219 
 1|=     '       =       '     B| --Championship Player's choices (your play: 1)
 2|  -       "       "       C E| best *E2  PIeNIĄ(C)A 78 98.32% 
 3|    -       '   '       - E T|  6.24 13H AlPINIĄ   74 97.54% 
 4|'     -       '     O R A N Y|  17.9 C7  P(R)Ą     26 95.29% IANI?
 5|        -         E K O   I  |  21.7 C12 (P)IPĄ    20 95.24% ANI?
 6|  "       "       H O   I Ł  |  25.3 F8  (ZAŚLE)PIĄ 20 94.22% ANI?
 7|    '       K O L E Ń   D A  |  26.2 D4  PIAN(Ę)   20 93.93% IĄ?
 8|= W R Ę C Z O N A     '     =|  27.6 J9  (M)Ą      17 93.49% PIANI?
 9|  S '     A '   Ć M I Ł A M  |  25.3 D4  PINI(Ę)   20 93.41% AĄ?
10|  U       Ś       "     D I P|  27.7 C6  PA(R)Ą    26 92.88% INI?
11|  W   S O L E       -        |  29.6 C5  NAI(R)Ą   26 92.73% PI?
12|K A P U J E S Z       -     '| --Tracking-----------------------------------
13|L   -       '   '       -    | ?ABCDEFGGHIIJMNNÓRRSTWWYYYZZZŹŻ  31
14|A -       "       "       -  |
15|T     '       =       '     =|
   ------------------------------

Maciej_Skrzypczak: Turn 9
   A B C D E F G H I J K L M N O      Pawel_Mazurek            DFGGYZZ   332 
   ------------------------------  -> Maciej_Skrzypczak        WYBJ      219 
 1|=     '       =       '     B| --Championship Player's choices (your play: 1)
 2|  -     P "       "       C E|  2.58*6B  WYB(I)J 18 0.7235% 
 3|    -   I   '   '       - E T|  2.98 3M  B(ET)   20 0.6820% WYJ
 4|'     - e     '     O R A N Y| best  3B  WYB(I)J 20 0.5429% 
 5|        N         E K O   I  |  1.12 4B  WYJ(e)B 18 0.4708% 
 6|  "     I "       H O   I Ł  |  6.96 4C  WJ(e)B  14 0.4215% Y
 7|    '   Ą   K O L E Ń   D A  |  6.33 3C  WB(I)J  16 0.4022% Y
 8|= W R Ę C Z O N A     '     =|  7.01 4D  W(e)BY  12 0.3506% J
 9|  S '   A A '   Ć M I Ł A M  |  11.4 4D  J(e)B   12 0.3420% WY
10|  U       Ś       "     D I P|  9.39 6C  WB(I)J  14 0.2896% Y
11|  W   S O L E       -        |  15.7 14A (A)J    8  0.2861% WYB
12|K A P U J E S Z       -     '| --Tracking-----------------------------------
13|L   -       '   '       -    | ?ACDEFGGHIIMNNÓRRSTWYYZZZŹŻ  27
14|A -       "       "       -  |
15|T     '       =       '     =|
   ------------------------------

Pawel_Mazurek: Turn 10
   A B C D E F G H I J K L M N O   -> Pawel_Mazurek            FGRSWZZ   332 
   ------------------------------     Maciej_Skrzypczak        AEHMRYŹ  237 
 1|=     '       =       '     B| --Championship Player's choices (your play: 1)
 2|  -     P "       "       C E|  22.4*3C  GZ(I)SZ   16 98.48% FRW
 3|    -   I   '   '       - E T|  6.09 4A  ZGRZ(e)W  16 96.97% FS
 4|'     - e     '     O R A N Y|  14.5 4B  WSZ(e)RZ  10 96.97% FG
 5|        N         E K O   I  |  20.7 C4  SZ(Y)F(R) 15 96.97% GRWZ
 6|  W Y B I J       H O   I Ł  |  24.6 F8  (ZAŚLE)SZ 14 96.97% FGRWZ
 7|    '   Ą   K O L E Ń   D A  |  33.8 14A (A)RF     14 96.21% GSWZZ
 8|= W R Ę C Z O N A     '     =|  8.95 4B  GRZ(e)SZ  14 95.83% FW
 9|  S '   A A '   Ć M I Ł A M  | 0.163 3M  F(ET)     28 95.45% GRSWZZ
10|  U       Ś       "     D I P|  9.34 4C  SZ(e)RZ   8  93.94% FGW
11|  W   S O L E       -        |  30.9 4C  RZ(e)SZ   8  93.94% FGW
12|K A P U J E S Z       -     '| --Tracking-----------------------------------
13|L   -       '   '       -    | ?ACDEGHIIMNNÓRTYYZŹŻ  20
14|A -       "       "       -  |
15|T     '       =       '     =|
   ------------------------------

Maciej_Skrzypczak: Turn 10
   A B C D E F G H I J K L M N O      Pawel_Mazurek            FIRTWZŻ  348 
   ------------------------------  -> Maciej_Skrzypczak        ÓC       237 
 1|=     '       =       '     B| --Championship Player's choices (your play: 1)
 2|  -     P "       "       C E| best *J9 (M)ÓC 19 1.515% 
 3|    G Z I S Z   '       - E T| 0.0836 L2 CÓ(RO) 9  0.0000% 
 4|'     - e     '     O R A N Y|  16.5 xch C      0  0.0000% Ó
 5|        N         E K O   I  |  37.5 9A Ó(S)  6  0.0000% C
 6|  W Y B I J       H O   I Ł  |  38.8 G1 ÓC(Z) 8  0.0000% 
 7|    '   Ą   K O L E Ń   D A  |  39.5 xch Ó     0  0.0000% C
 8|= W R Ę C Z O N A     '     =|  43.2 B5 Ó(W)  6  0.0000% C
 9|  S '   A A '   Ć M I Ł A M  |  51.6 xch CÓ    0  0.0000% 
10|  U       Ś       "     D I P| --Tracking-----------------------------------
11|  W   S O L E       -        | ?ADEFGHIIMNNRRTWYYZŹŻ  21
12|K A P U J E S Z       -     '|
13|L   -       '   '       -    |
14|A -       "       "       -  |
15|T     '       =       '     =|
   ------------------------------

Pawel_Mazurek: Turn 11
   A B C D E F G H I J K L M N O   -> Pawel_Mazurek            FGMRWŻ?  348 
   ------------------------------     Maciej_Skrzypczak        ADHNRYZ   256 
 1|=     '       =       '     B| --Championship Player's choices (your play: 2)
 2|  -     P "       "       C E| best  xch FGRWŻ 0  100.0% M?
 3|    G Z I S Z   '       - E T|  9.18*3M  F(ET)  28 100.0% GMRWŻ?
 4|'     - e     '     O R A N Y|  17.5 10A F(U)G  11 100.0% MRWŻ?
 5|        N         E K O   I  |  21.7 14A (A)MF  16 100.0% GRWŻ?
 6|  W Y B I J       H O   I Ł  |  24.3 xch FMRWŻ 0  100.0% G?
 7|    '   Ą   K O L E Ń   D A  |  24.6 14A (A)Ż  12 100.0% FGMRW?
 8|= W R Ę C Z O N A     '     =|  25.3 xch FGMWŻ 0  100.0% R?
 9|  S '   A A '   Ć M I Ł A M  |  28.3 xch FGMRWŻ 0  100.0% ?
10|  U       Ś       Ó     D I P|  33.9 3M  M(ET)  16 100.0% FGRWŻ?
11|  W   S O L E     C -        |  44.3 xch FGMRŻ 0  100.0% W?
12|K A P U J E S Z       -     '| --Tracking-----------------------------------
13|L   -       '   '       -    | ADEHIINNRTYYZŹ  14
14|A -       "       "       -  |
15|T     '       =       '     =|
   ------------------------------

Maciej_Skrzypczak: Turn 11
   A B C D E F G H I J K L M N O      Pawel_Mazurek            ?EGMRWŻ  376 
   ------------------------------  -> Maciej_Skrzypczak        ATRZY     256 
 1|=     '       =       '     B| --Championship Player's choices (your play: 1)
 2|  -     P "       "       C E| best *O10 (P)ATRZY 33 6.818% 
 3|    G Z I S Z   '       F E T|  64.6 14A (A)TARY  14 1.515% Z
 4|'     - e     '     O R A N Y|  61.6 O7  TA       14 0.7576% RZY
 5|        N         E K O   I  |  33.9 14A (A)RATY  14 0.0000% Z
 6|  W Y B I J       H O   I Ł  |  48.9 C12 (P)YTA   14 0.0000% RZ
 7|    '   Ą   K O L E Ń   D A  |  49.8 13C AR       15 0.0000% TZY
 8|= W R Ę C Z O N A     '     =|  51.7 F1  TA(S)Z   13 0.0000% RY
 9|  S '   A A '   Ć M I Ł A M  |  54.3 F3  (S)ZY(J) 11 0.0000% ATR
10|  U       Ś       Ó     D I P|  55.5 C12 (P)YT    12 0.0000% ARZ
11|  W   S O L E     C -        |  57.5 N9  (MI)ZARY 16 0.0000% T
12|K A P U J E S Z       -     '| --Tracking-----------------------------------
13|L   -       '   '       -    | ?DEGHIIMNNRWYŹŻ  15
14|A -       "       "       -  |
15|T     '       =       '     =|
   ------------------------------

Pawel_Mazurek: Turn 12
   A B C D E F G H I J K L M N O   -> Pawel_Mazurek            WGRYŻM?  376 
   ------------------------------     Maciej_Skrzypczak        DEHIINN   289 
 1|=     '       =       '     B| --Championship Player's choices (your play: 7)
 2|  -     P "       "       C E| best  11J (C)YG 14 100.0% WRŻM?
 3|    G Z I S Z   '       F E T|  9.72 K9  (I)W  8  100.0% GRYŻM?
 4|'     - e     '     O R A N Y|  15.7 7M  (DA)G 6  100.0% WRYŻM?
 5|        N         E K O   I  |  43.8 14A (A)G  8  100.0% WRYŻM?
 6|  W Y B I J       H O   I Ł  |  45.8 D11 (SU)M 6  100.0% WGRYŻ?
 7|    '   Ą   K O L E Ń   D A  |  51.6 14A (A)M  6  100.0% WGRYŻ?
 8|= W R Ę C Z O N A     '     =|  57.8*14A (A)Ż 12 100.0% WGRYM?
 9|  S '   A A '   Ć M I Ł A M  |  61.5 N9  (MI)M 8  100.0% WGRYŻ?
10|  U       Ś       Ó     D I P|  62.5 H6  Ż(ON) 7  100.0% WGRYM?
11|  W   S O L E     C -       A|  65.0 15M RŻ(Y) 8  100.0% WGYM?
12|K A P U J E S Z       -     T| --Tracking-----------------------------------
13|L   -       '   '       -   R| DEHIINNŹ  8
14|A -       "       "       - Z|
15|T     '       =       '     Y|
   ------------------------------

Maciej_Skrzypczak: Turn 12
   A B C D E F G H I J K L M N O      Pawel_Mazurek            ?GIMRWŹ  388 
   ------------------------------  -> Maciej_Skrzypczak        NE        289 
 1|=     '       =       '     B| --Championship Player's choices (your play: 7)
 2|  -     P "       "       C E| best  11J (C)NE    8  
 3|    G Z I S Z   '       F E T|  1.39 11J (C)EN    8  
 4|'     - e     '     O R A N Y|  3.01 6B  (WYBIJ)E 15 N
 5|        N         E K O   I  |  6.98 B14 (Ż)E    9  N
 6|  W Y B I J       H O   I Ł  |  10.8 C3  (G)EN(Y) 7  
 7|    '   Ą   K O L E Ń   D A  |  14.9 C12 (P)E     6  N
 8|= W R Ę C Z O N A     '     =|  14.9*N14 EN       11 
 9|  S '   A A '   Ć M I Ł A M  |  15.0 15A (T)EN    10 
10|  U       Ś       Ó     D I P|  15.2 G3  (Z)EN    3  
11|  W   S O L E     C -       A|  22.6 H5  NE(ON)   4  
12|K A P U J E S Z       -     T| --Tracking-----------------------------------
13|L   -       '   '       -   R| ?DGHIIMNRWYŹ  12
14|A Ż       "       "       - Z|
15|T     '       =       '     Y|
   ------------------------------

Pawel_Mazurek: Turn 13
   A B C D E F G H I J K L M N O   -> Pawel_Mazurek            WGRYMŹ?  388 
   ------------------------------     Maciej_Skrzypczak        DHIIN     300 
 1|=     '       =       '     B| --Championship Player's choices (your play: urp)
 2|  -     P "       "       C E| best  F8  (ZAŚLE)MY 18 100.0% WGRŹ?
 3|    G Z I S Z   '       F E T|  15.0 H12 (Z)WoŹ   33 100.0% GRYM
 4|'     - e     '     O R A N Y|  17.0 H12 (Z)MYW    18 100.0% GRŹ?
 5|        N         E K O   I  |  23.0 M12 RYG       17 100.0% WMŹ?
 6|  W Y B I J       H O   I Ł  |  41.0 15K ŹGa(NY)  18 100.0% WRYM
 7|    '   Ą   K O L E Ń   D A  |  47.0 F8  (ZAŚLE)My 12 100.0% WGRYŹ
 8|= W R Ę C Z O N A     '     =|  59.0 13C oM        14 100.0% WGRYŹ
 9|  S '   A A '   Ć M I Ł A M  |  59.0 13C iM        14 100.0% WGRYŹ
10|  U       Ś       Ó     D I P|  59.0 G5  Mę(KO)   15 100.0% WGRYŹ
11|  W   S O L E     C -       A|  38.9*H12 (Z)WóŹ  33 0.0000% GRYM
12|K A P U J E S Z       -     T| --Tracking-----------------------------------
13|L   -       '   '       -   R| DHIIN  5
14|A Ż       "       "       E Z|
15|T     '       =       '   N Y|
   ------------------------------

Maciej_Skrzypczak: Turn 13
   A B C D E F G H I J K L M N O      Pawel_Mazurek            GRYM      421 
   ------------------------------  -> Maciej_Skrzypczak        DHIIN     300 
 1|=     '       =       '     B| --Championship Player's choices (your play: 9)
 2|  -     P "       "       C E| best  K11 IND     14 HI
 3|    G Z I S Z   '       F E T| best  F1  HI(S)   12 DIN
 4|'     - e     '     O R A N Y|  3.00 11J (C)HI   12 DIN
 5|        N         E K O   I  |  3.00 11I I(C)H   12 DIN
 6|  W Y B I J       H O   I Ł  |  3.00 I3  IND     11 HI
 7|    '   Ą   K O L E Ń   D A  |  6.00 5A  HI      6  DIN
 8|= W R Ę C Z O N A     '     =|  6.00 H4  NIH(ON) 8  DI
 9|  S '   A A '   Ć M I Ł A M  |  7.00 B4  HI(W)   5  DIN
10|  U       Ś       Ó     D I P|  16.0*15F ID(Ź)  12 HIN
11|  W   S O L E     C -       A|  17.0 K11 ID      12 HIN
12|K A P U J E S Z       -     T| --Tracking-----------------------------------
13|L   -       ' W '       -   R| GMRY  4
14|A Ż       "   ó   "       E Z|
15|T     '       Ź       '   N Y|
   ------------------------------

Pawel_Mazurek: Turn 14
   A B C D E F G H I J K L M N O   -> Pawel_Mazurek            GMRY      421 
   ------------------------------     Maciej_Skrzypczak        HIN       312 
 1|=     '       =       '     B| --Championship Player's choices (your play: 8)
 2|  -     P "       "       C E| best  5H  GR(EKO) 8  100.0% MY
 3|    G Z I S Z   '       F E T|  2.00 H5  GR(ON)  6  100.0% MY
 4|'     - e     '     O R A N Y|  8.00 G2  G(Z)Y   6  100.0% MR
 5|        N         E K O   I  |  10.0 M12 RYG     17 100.0% M
 6|  W Y B I J       H O   I Ł  |  11.0 H6  G(ON)   5  100.0% MRY
 7|    '   Ą   K O L E Ń   D A  |  12.0 H6  M(ON)   4  100.0% GRY
 8|= W R Ę C Z O N A     '     =|  13.0 14D RYM     16 100.0% G
 9|  S '   A A '   Ć M I Ł A M  |  14.0*O7  MY      17 100.0% GR
10|  U       Ś       Ó     D I P|  15.0 15F (IDŹ)MY 16 100.0% GR
11|  W   S O L E     C -       A|  15.0 11J (C)YG   14 100.0% MR
12|K A P U J E S Z       -     T| --Tracking-----------------------------------
13|L   -       ' W '       -   R| HIN  3
14|A Ż       "   ó   "       E Z|
15|T     '   I D Ź       '   N Y|
   ------------------------------

Maciej_Skrzypczak: Turn 14
   A B C D E F G H I J K L M N O      Pawel_Mazurek            GR        438 
   ------------------------------  -> Maciej_Skrzypczak        HIN       312 
 1|=     '       =       '     B| --Championship Player's choices (your play: 4)
 2|  -     P "       "       C E| best  H4  NIH(ON) 8  
 3|    G Z I S Z   '       F E T|  19.0 11J (C)HI   12 N
 4|'     - e     '     O R A N Y|  19.0 11I I(C)H   12 N
 5|        N         E K O   I  |  19.0*F1  HI(S)   12 N
 6|  W Y B I J       H O   I Ł  |  20.0 12M HI(T)   6  N
 7|    '   Ą   K O L E Ń   D A M|  21.0 14E HI      10 N
 8|= W R Ę C Z O N A     '     Y|  23.0 F14 H(I)    10 IN
 9|  S '   A A '   Ć M I Ł A M  |  24.0 10A H(U)N   7  I
10|  U       Ś       Ó     D I P|  25.0 K11 IN      10 H
11|  W   S O L E     C -       A|  25.0 5A  HI      6  N
12|K A P U J E S Z       -     T| --Tracking-----------------------------------
13|L   -       ' W '       -   R| GR  2
14|A Ż       "   ó   "       E Z|
15|T     '   I D Ź       '   N Y|
   ------------------------------

Pawel_Mazurek: Turn 15
   A B C D E F G H I J K L M N O   -> Pawel_Mazurek            GR        438 
   ------------------------------     Maciej_Skrzypczak        N         324 
 1|=     '   H   =       '     B| --Championship Player's choices (your play: 2)
 2|  -     P I       "       C E| best  13M GR(R)   13 100.0% 
 3|    G Z I S Z   '       F E T|  5.00*5H  GR(EKO) 8  100.0% 
 4|'     - e     '     O R A N Y|  6.00 10A R(U)G   7  100.0% 
 5|        N         E K O   I  |  6.00 10A G(U)R   7  100.0% 
 6|  W Y B I J       H O   I Ł  |  7.00 H5  GR(ON)  6  100.0% 
 7|    '   Ą   K O L E Ń   D A M|  18.0 14M G(EZ)   5  100.0% R
 8|= W R Ę C Z O N A     '     Y|  18.0 H6  G(ON)   5  100.0% R
 9|  S '   A A '   Ć M I Ł A M  |  22.0 D11 (SU)R   5  100.0% G
10|  U       Ś       Ó     D I P| --Tracking-----------------------------------
11|  W   S O L E     C -       A| N  1
12|K A P U J E S Z       -     T|
13|L   -       ' W '       -   R|
14|A Ż       "   ó   "       E Z|
15|T     '   I D Ź       '   N Y|
   ------------------------------

   A B C D E F G H I J K L M N O   -> Pawel_Mazurek                      448 
   ------------------------------     Maciej_Skrzypczak        N         324 
 1|=     '   H   =       '     B| 
 2|  -     P I       "       C E|  Game over.
 3|    G Z I S Z   '       F E T| 
 4|'     - e     '     O R A N Y| --Tracking-----------------------------------
 5|        N     G R E K O   I  | N  1
 6|  W Y B I J       H O   I Ł  |
 7|    '   Ą   K O L E Ń   D A M|
 8|= W R Ę C Z O N A     '     Y|
 9|  S '   A A '   Ć M I Ł A M  |
10|  U       Ś       Ó     D I P|
11|  W   S O L E     C -       A|
12|K A P U J E S Z       -     T|
13|L   -       ' W '       -   R|
14|A Ż       "   ó   "       E Z|
15|T     '   I D Ź       '   N Y|
   ------------------------------

`;
