import React, { Component } from 'react';
import '../css/Board.css'

const boardFields = () => (
  <div className="board">
    <div className="up-coordinates">
      <div className="coordinate-x">1</div>
      <div className="coordinate-x">2</div>
      <div className="coordinate-x">3</div>
      <div className="coordinate-x">4</div>
      <div className="coordinate-x">5</div>
      <div className="coordinate-x">6</div>
      <div className="coordinate-x">7</div>
      <div className="coordinate-x">8</div>
      <div className="coordinate-x">9</div>
      <div className="coordinate-x">10</div>
      <div className="coordinate-x">11</div>
      <div className="coordinate-x">12</div>
      <div className="coordinate-x">13</div>
      <div className="coordinate-x">14</div>
      <div className="coordinate-x">15</div>
    </div>
    <div className="left-coordinates">
      <div className="coordinate-y">A</div>
      <div className="coordinate-y">B</div>
      <div className="coordinate-y">C</div>
      <div className="coordinate-y">D</div>
      <div className="coordinate-y">E</div>
      <div className="coordinate-y">F</div>
      <div className="coordinate-y">G</div>
      <div className="coordinate-y">H</div>
      <div className="coordinate-y">I</div>
      <div className="coordinate-y">J</div>
      <div className="coordinate-y">K</div>
      <div className="coordinate-y">L</div>
      <div className="coordinate-y">M</div>
      <div className="coordinate-y">N</div>
      <div className="coordinate-y">O</div>
    </div>
    <div className="field w3"><span>POTRÓJNA PREMIA SŁOWNA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field l2"><span>PODWÓJNA PREMIA LITEROWA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field w3"><span>POTRÓJNA PREMIA SŁOWNA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field l2"><span>PODWÓJNA PREMIA LITEROWA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field w3"><span>POTRÓJNA PREMIA SŁOWNA</span></div>
    <div className="field"></div>
    <div className="field w2"><span>PODWÓJNA PREMIA SŁOWNA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field l3"><span>POTRÓJNA PREMIA LITEROWA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field l3"><span>POTRÓJNA PREMIA LITEROWA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field w2"><span>PODWÓJNA PREMIA SŁOWNA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field w2"><span>PODWÓJNA PREMIA SŁOWNA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field l2"><span>PODWÓJNA PREMIA LITEROWA</span></div>
    <div className="field"></div>
    <div className="field l2"><span>PODWÓJNA PREMIA LITEROWA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field w2"><span>PODWÓJNA PREMIA SŁOWNA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field l2"><span>PODWÓJNA PREMIA LITEROWA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field w2"><span>PODWÓJNA PREMIA SŁOWNA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field l2"><span>PODWÓJNA PREMIA LITEROWA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field w2"><span>PODWÓJNA PREMIA SŁOWNA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field l2"><span>PODWÓJNA PREMIA LITEROWA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field w2"><span>PODWÓJNA PREMIA SŁOWNA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field w2"><span>PODWÓJNA PREMIA SŁOWNA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field l3"><span>POTRÓJNA PREMIA LITEROWA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field l3"><span>POTRÓJNA PREMIA LITEROWA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field l3"><span>POTRÓJNA PREMIA LITEROWA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field l3"><span>POTRÓJNA PREMIA LITEROWA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field l2"><span>PODWÓJNA PREMIA LITEROWA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field l2"><span>PODWÓJNA PREMIA LITEROWA</span></div>
    <div className="field"></div>
    <div className="field l2"><span>PODWÓJNA PREMIA LITEROWA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field l2"><span>PODWÓJNA PREMIA LITEROWA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field w3"><span>POTRÓJNA PREMIA SŁOWNA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field l2"><span>PODWÓJNA PREMIA LITEROWA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field center"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field l2"><span>PODWÓJNA PREMIA LITEROWA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field w3"><span>POTRÓJNA PREMIA SŁOWNA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field l2"><span>PODWÓJNA PREMIA LITEROWA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field l2"><span>PODWÓJNA PREMIA LITEROWA</span></div>
    <div className="field"></div>
    <div className="field l2"><span>PODWÓJNA PREMIA LITEROWA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field l2"><span>PODWÓJNA PREMIA LITEROWA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field l3"><span>POTRÓJNA PREMIA LITEROWA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field l3"><span>POTRÓJNA PREMIA LITEROWA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field l3"><span>POTRÓJNA PREMIA LITEROWA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field l3"><span>POTRÓJNA PREMIA LITEROWA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field w2"><span>PODWÓJNA PREMIA SŁOWNA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field w2"><span>PODWÓJNA PREMIA SŁOWNA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field l2"><span>PODWÓJNA PREMIA LITEROWA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field w2"><span>PODWÓJNA PREMIA SŁOWNA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field l2"><span>PODWÓJNA PREMIA LITEROWA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field w2"><span>PODWÓJNA PREMIA SŁOWNA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field l2"><span>PODWÓJNA PREMIA LITEROWA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field w2"><span>PODWÓJNA PREMIA SŁOWNA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field l2"><span>PODWÓJNA PREMIA LITEROWA</span></div>
    <div className="field"></div>
    <div className="field l2"><span>PODWÓJNA PREMIA LITEROWA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field w2"><span>PODWÓJNA PREMIA SŁOWNA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field w2"><span>PODWÓJNA PREMIA SŁOWNA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field l3"><span>POTRÓJNA PREMIA LITEROWA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field l3"><span>POTRÓJNA PREMIA LITEROWA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field w2"><span>PODWÓJNA PREMIA SŁOWNA</span></div>
    <div className="field"></div>
    <div className="field w3"><span>POTRÓJNA PREMIA SŁOWNA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field l2"><span>PODWÓJNA PREMIA LITEROWA</span></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field"></div>
    <div className="field w3"><span>POTRÓJNA PREMIA SŁOWNA</span></div>
    <div className="field down"></div>
    <div className="field down"></div>
    <div className="field down"></div>
    <div className="field l2"><span>PODWÓJNA PREMIA LITEROWA</span></div>
    <div className="field down"></div>
    <div className="field down"></div>
    <div className="field w3"><span>POTRÓJNA PREMIA SŁOWNA</span></div>
  </div>
)

class Board extends Component {
  render() {
    return (
      <>
        <div className="board-wrapper">
          <canvas> </canvas>
          {boardFields()}
        </div>
      </>
    );
  }
}


export default Board;
